/* eslint-disable */
// Convex API stub — auto-generated by `npx convex codegen`
// Replace with real generated code after running `npx convex dev`

export const api = {
  waitlist: {
    getCount: "waitlist:getCount" as any,
    join: "waitlist:join" as any,
    getReferralStats: "waitlist:getReferralStats" as any,
    getAll: "waitlist:getAll" as any,
  },
} as const;

export const internal = api;
